### ISSUE TITLE
Detecting language

### ISSUE THREAD

**Issue by betalk-ir** [luceos/flarum-simple-spam-tools#1]
Hi
This is good tool for controlling spammers but can you add language detection?
Flarum spammers (as i see topics in flarum community), mostly are from china. So if we could detect new topic's language this could help to prevent spammers.

**Comment by luceos** [comment]
@betalk-ir language detection in itself won't help. Do you want to keep messages for approval in case they aren't in any of the languages configured on the community? Or do you want to be able to explicitly add a certain language to a block list?

This ignores the technical complication of identifying languages, but I'll do some research.

**Comment by betalk-ir** [comment]
> Or do you want to be able to explicitly add a certain language to a block list?

Yes this is what we can do for stopping spammers from some languages. For example my forum is Arabic language and some languages are spam for us. like Chinese language.
Recently, the number of spammers who are spamming in Chinese or Japanese language in Flarum has increased a lot.

Identifying the language of new topics can be one of the best ways to prevent irrelevant topics from being posted in the forum that all of topics are in specific language.

**Comment by luceos** [comment]
Yeah, it's a great idea. I've almost completed the feature and I'd love to get your feedback once it's done.

**Comment by luceos** [comment]
Can you try this out? 

```
composer require luceos/flarum-simple-spam-tools
```

This should install `0.1.1`. No change in the `extend.php` is needed ;)

**Comment by betalk-ir** [comment]
Wow, This is working now. Fast and clean.
I think this worth to publish as stable extension.

**Comment by luceos** [comment]
It would require a UX and that takes a ton of time ;) Until it has matured I might as well keep it this way.
